### ISSUE TITLE
CVS version of NEMO

### ISSUE THREAD

**Issue by teuben** [jobovy/nemo#1]
I'm planning to retire the CVS version of NEMO, and move to git. But I see you have an import. How to proceed?

**Comment by jobovy** [comment]
Hi Peter,

That's great, git would be a great improvement over CVS! What do you mean by "I see you have an import"? If it's that I'm depending on the CVS version, that's not a problem (this repository is just a convenient version of a snapshot of NEMO from a year and half ago, nothing more; I would happily switch to an official git version).

**Comment by teuben** [comment]
Great, you can clone that one. I once tested this, as it can utiliize the CVS history (which I probably don't want to loose).

I also have a branch sitting in CVS to work on the better storage model for images (to match fits), but that's an unfinished experiment. Back in the old days I of course didn't realize the usefulness of fits as much as now, where I realized that for astronomical images and cubes NEMO would become terribly inefficient for large data.

I'll keep you posted. I guess after that you can fork and commit on a branch for any new suggestions :-)
peter
