### ISSUE TITLE
NEMO in github

### ISSUE THREAD

**Issue by teuben** [jobovy/nemo#2]
I had all but forgotten about this repo. During my ESO trip last winter, I converted NEMO's CSM from CVS to git, under github.   I should glance over the intro comments here and make sure I take some of the ideas here back.

https://github.com/teuben/nemo

**Comment by jobovy** [comment]
That's great! I'll be sure to put a link to the official NEMO repository in the README here.

**Comment by jobovy** [comment]
I added a link to the official repository in https://github.com/jobovy/nemo/commit/92d3711f9c221f73394a85602322cf9f4194ce7a and encouraged people to use that version instead.
